package automod_legacy

// This list is in alphabethical order
// Open a pr or bug me on discord if you want a word added
var BuiltinSwearWords = map[string]bool{
	"anal":        true,
	"anus":        true,
	"arse":        true,
	"ass":         true,
	"b1tch":       true,
	"ballsack":    true,
	"bastard":     true,
	"bitch":       true,
	"biatch":      true,
	"blowjob":     true,
	"bollock":     true,
	"bollok":      true,
	"boner":       true,
	"boob":        true,
	"boobs":       true,
	"buttplug":    true,
	"clitoris":    true,
	"cock":        true,
	"cum":         true,
	"cunt":        true,
	"dick":        true,
	"dildo":       true,
	"dyke":        true,
	"erection":    true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"fellate":     true,
	"fellatio":    true,
	"felching":    true,
	"fuck":        true,
	"fucks":       true,
	"fudgepacker": true,
	"genitals":    true,
	"hell":        true,
	"jerk":        true,
	"jizz":        true,
	"knobend":     true,
	"labia":       true,
	"masturbate":  true,
	"muff":        true,
	"nigger":      true,
	"nigga":       true,
	"penis":       true,
	"piss":        true,
	"poop":        true,
	"pube":        true,
	"pussy":       true,
	"queer":       true,
	"scrotum":     true,
	"sex":         true,
	"shit":        true,
	"sh1t":        true,
	"slut":        true,
	"smegma":      true,
	"spunk":       true,
	"tit":         true,
	"tranny":       true,
	"trannies":     true,
	"tosser":      true,
	"turd":        true,
	"twat":        true,
	"vagina":      true,
	"wank":        true,
	"whore":       true,
	"tits":        true,
	"titty":       true,
	"asshole":     true,
	"fvck":        true,
	"asshat":      true,
	"pu55y":       true,      
"كس":       true,
"عير ":       true,
"شرج":       true,
"شرموطه":       true,
"شرموطة":       true,
"شرموط":       true,
"شرموطا":       true,
"كحبه ":       true,
"كحبة":       true,
"كواد ":       true,
"ابو العير":       true,
"ابو العيور":       true,
"كس اختك":       true,
"كسختك":       true,
"كس امك":       true,
"كسمك":       true,
"كس أمك":       true,
"كس إمك":       true,
"كس أختك":       true,
"كس إختك":       true,
"كس آختك":       true,
"قضيب":       true,
"عير":       true,
"عيور":       true,
"طوب عير":       true,
"دعبل عير":       true,
"دعابل عير":       true,
"دعبولات عير ":       true,
"دعبولات عيري":       true,
"دعابل عيري":       true,
"🖕":       true,
"🐟":       true,
"🍑":       true,
"🍆":       true,
"🍌":       true,
"🥖":       true,
"منيوج":       true,
"منيوجة":       true,
"منيوجه":       true,


}
